config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(params[:flat_params])
    @flat.save
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
     <h1>All our flats(4)</h1>
  <div class="container d-flex">
    <% @flats.each do |flat| %>
    <div>
      <div class="card" style="height: 200px" >
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
          <p><%= link_to 'More Info', flat_path(flat), class: "btn btn-primary" %></p>
        </div>
      </div>
    </div>
    <% end %>
</div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div>
  <div class="card" style="height: 200px" >
    <div class="card-body">
      <h5 class="card-title"><%= @flat.name %></h5>
      <p class="card-text"><%= @flat.address %></p>
      <p class="card-text"><%= @flat.description %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand">Simple Airbnb</a>
        <form class="d-flex">
          <button class="btn btn-outline-success" type="submit"><%= link_to "Add Flat", new_flat_path %></button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>